version: '3.4'

services:
  mvccore:
    image: ${DOCKER_REGISTRY-}mvccore
    container_name: wikifs
    build:
      context: .
      dockerfile: MvcCore/Dockerfile
    ports:
      - "5001:80"
    networks:
      - databasefs
    environment:
      - ConnectionString=Server=sqlserverfs;Database=wikifs;User Id=sa;Password=Test3211!;
  sqlserverfs:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: sqlserverfs
    build:
      context: .
      dockerfile: MvcCore/DockerDB/Dockerfile
    ports:
      - "${DOCKER_SQL_PORT:-1433}:1433"
    volumes:
      - mssqldata:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Test3211!

    networks:
      databasefs:
        aliases:
          - sqlserverfs

volumes:
  mssqldata:
networks:
  databasefs: